version: "3.7"
services:
  forum_client:
    build: .
    container_name: "forum_client"
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - ./:/app
    tty: true
    networks:
      - forum_network

networks:
  forum_network:
    external: true
