version: "3.8"
services:
  forum_database:
    container_name: forum_db
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
      - forum_network

  forum_server:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: forum_server
    restart: on-failure
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    depends_on:
      - forum_database
    env_file:
      - .env
    networks:
      - forum_network

volumes:
  mysql_data:

networks:
  forum_network:
    external: true
